default: &default
  adapter: postgresql
  encoding: unicode
  username: hackippides
  password: hackippides1234
  host: localhost
  port: 5432

development:
  <<: *default
  pool: 5
  database: hackthon_app_development

test:
  <<: *default
  pool: 5
  database: hackthon_app_test

production:
  <<: *default
  database: quiron_production
  username: quiron
  password: <%= ENV['QUIRON_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
