# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd4bf749bf6900c853d7d927eb1ea89e33efa509e9d7fc2016087ba78af2882c98334a49fccee695daba10dc0b9734e0bb96087430a345abad89044a781300d6

test:
  secret_key_base: dc4064a75a53aa920a69f8802b2f44fd714af9afc9f7677042f39861a09797dfd0f0fe0a01c4c5c03df2e2960b398fa046a58ba2a33252a40990d35c3faf435e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
